### ISSUE TITLE
How to set up multiple web-suite  app users?

### ISSUE THREAD

**Issue by gsbiel** [openflighthpc/openflight-slurm-multinode#8]
Hello!

I have been trying to setup a slurm-multinode cluster with multi user support.
I managed to enable the IPA integration and could successfully create new users there, but those users can not log in to the web-suite page. I can only log in using the default user created during the deployment of the cluster ("flight" user). 
Is that the normal behavior?

Is it possible to add and manage more users in the web-suite app?

PS: I could create SSH keys for IPA users and could ssh to the gateway node using those keys though. But I was expecting those users to also be able to log in to the web-suite app.

I appreciate any support on this, thanks!

**Comment by ColonelPanics** [comment]
Hi gsbiel! 

Are you running the playbook directly or installing [`flight profile`](github.com/openflighthpc/flight-profile) or running [Flight Solo](https://www.openflighthpc.org/latest/docs/flight-solo/)? The playbook supplements some of our other tools in order to perform system configuration in standardised processes. 

The Flight Web Suite integrates with PAM on the system which it is setup on. In our tools we enforce a separate "login" server identity to "ipa" server identity in line with our [HPC concepts](https://www.openflighthpc.org/latest/docs/hpc-concepts/network-hardware/#node-types). 

I'd presume that logging in to Flight Web Suite as an IPA user will work as long as: 
- The system running "Flight Web Suite" is not also the IPA server configured by this playbook (as it won't setup the IPA server as a system which all users can login to, keeping it as an "admin only" system)
- The IPA users have had passwords set
    - When a password is set with `ipa passwd USERNAME` it will be a temporary one that IPA will require the user to change on first login
    - The user will then need to login via SSH to the system with the password to be prompted into changing their password, once the password is changed then password authentication will work in Flight Web Suite

Based on your note that users can login using SSH keys I am going to assume that the issue you're hitting is with the latter points listed above - could you try setting a password for the IPA users, logging in via SSH, setting a new password and then trying Flight Web Suite login? 

Hope this helps!

**Comment by gsbiel** [comment]
Hey @ColonelPanicks! thanks for the quick response
Yeah, I am running Flight Solo on OpenStack.
As you pointed, I was missing that SSH step after creating the password for the users. It is working now :)
Thanks a lot for the help!

**Comment by VoxSecundus** [comment]
Closing this, as it looks like @ColonelPanicks has solved the issue. Thanks for your inquiry, @gsbiel !

**Comment by ColonelPanics** [comment]
Additionally, the documentation for the next release of Solo now contains some additional information and reference for managing IPA users in SLURM Multinode clusters - https://www.openflighthpc.org/2024.2/docs/flight-solo/cluster-build-methods/slurm-multinode-openstack/#adding-ipa-users
